language: node_js
node_js:
  - 10
install:
  - npm install

stages:
  - build
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
